### ISSUE TITLE
How to use for a newbie

### ISSUE THREAD

**Issue by OPatrick** [instrumentisto/flex-sdk-docker-image#4]
Hello, 
I am struggling to install Flex-SDK 4.16.0 on a Windows PC (a customer asked me to resolve a bug on an old install)
When I download and install the image with the right tag, how can I use it then?
How to use it with Intellij Idea or even Flash Builder on windows??

Thanks for your help

**Comment by tyranron** [comment]
@OPatrick you can't use this image in integration with Intellij Idea or Flash Builder. If you want code autocomplete and operations integration you need to install Flex SDK in your host system where your IDE is installed. Unfortunately, I cannot help you with that, as I don't use Windows.

All this Docker image is about is to freeze concrete build environment inside. That's all. You may use it to build your project using `mxmlc` directly or via `gradle` as [README explains](https://github.com/instrumentisto/flex-sdk-docker-image#how-to-use-this-image). Commonly, this image is used on CI environments.

**Comment by OPatrick** [comment]
OK, thanks

Le 07/06/2018 à 10:06, Kai Ren a écrit :
